//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class User : object
    {
        
        private int IdField;
        
        private string NomeField;
        
        private string EmailField;
        
        private string PasswordField;
        
        private string RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fornecedor", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Fornecedor : object
    {
        
        private int FornecedorIDField;
        
        private string FornecedorNomeField;
        
        private int ContactoField;
        
        private string MoradaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FornecedorID
        {
            get
            {
                return this.FornecedorIDField;
            }
            set
            {
                this.FornecedorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FornecedorNome
        {
            get
            {
                return this.FornecedorNomeField;
            }
            set
            {
                this.FornecedorNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Morada
        {
            get
            {
                return this.MoradaField;
            }
            set
            {
                this.MoradaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Produto : object
    {
        
        private int ProdutoIDField;
        
        private string ProdutoNomeField;
        
        private string DescricaoField;
        
        private float PrecoField;
        
        private int StockField;
        
        private string EstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoID
        {
            get
            {
                return this.ProdutoIDField;
            }
            set
            {
                this.ProdutoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdutoNome
        {
            get
            {
                return this.ProdutoNomeField;
            }
            set
            {
                this.ProdutoNomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float Preco
        {
            get
            {
                return this.PrecoField;
            }
            set
            {
                this.PrecoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Encomenda", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Encomenda : object
    {
        
        private int EncomendaIDField;
        
        private System.DateTime DataField;
        
        private int FornecedorIDField;
        
        private int UtilizadorIDField;
        
        private string EstadoField;
        
        private SOAPServiceReference.DetalheEncomenda[] DetalhesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EncomendaID
        {
            get
            {
                return this.EncomendaIDField;
            }
            set
            {
                this.EncomendaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int FornecedorID
        {
            get
            {
                return this.FornecedorIDField;
            }
            set
            {
                this.FornecedorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int UtilizadorID
        {
            get
            {
                return this.UtilizadorIDField;
            }
            set
            {
                this.UtilizadorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public SOAPServiceReference.DetalheEncomenda[] Detalhes
        {
            get
            {
                return this.DetalhesField;
            }
            set
            {
                this.DetalhesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalheEncomenda", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class DetalheEncomenda : object
    {
        
        private int EncomendaIDField;
        
        private int ProdutoIDField;
        
        private int QuantidadeField;
        
        private float PrecoTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EncomendaID
        {
            get
            {
                return this.EncomendaIDField;
            }
            set
            {
                this.EncomendaIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoID
        {
            get
            {
                return this.ProdutoIDField;
            }
            set
            {
                this.ProdutoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float PrecoTotal
        {
            get
            {
                return this.PrecoTotalField;
            }
            set
            {
                this.PrecoTotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimento", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Movimento : object
    {
        
        private int MovimentoIDField;
        
        private int ProdutoIDField;
        
        private System.DateTime DataField;
        
        private string TipoInOutField;
        
        private int QuantidadeField;
        
        private int UtilizadorIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovimentoID
        {
            get
            {
                return this.MovimentoIDField;
            }
            set
            {
                this.MovimentoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoID
        {
            get
            {
                return this.ProdutoIDField;
            }
            set
            {
                this.ProdutoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string TipoInOut
        {
            get
            {
                return this.TipoInOutField;
            }
            set
            {
                this.TipoInOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int UtilizadorID
        {
            get
            {
                return this.UtilizadorIDField;
            }
            set
            {
                this.UtilizadorIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPServiceReference.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestarConexao", ReplyAction="http://tempuri.org/IService/TestarConexaoResponse")]
        System.Threading.Tasks.Task<string> TestarConexaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidateUser", ReplyAction="http://tempuri.org/IService/ValidateUserResponse")]
        System.Threading.Tasks.Task<bool> ValidateUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUserByEmail", ReplyAction="http://tempuri.org/IService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.User> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUser", ReplyAction="http://tempuri.org/IService/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(string nome, string email, string password, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllFornecedores", ReplyAction="http://tempuri.org/IService/GetAllFornecedoresResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Fornecedor[]> GetAllFornecedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetFornecedorById", ReplyAction="http://tempuri.org/IService/GetFornecedorByIdResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Fornecedor> GetFornecedorByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFornecedor", ReplyAction="http://tempuri.org/IService/AddFornecedorResponse")]
        System.Threading.Tasks.Task<bool> AddFornecedorAsync(SOAPServiceReference.Fornecedor fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateFornecedor", ReplyAction="http://tempuri.org/IService/UpdateFornecedorResponse")]
        System.Threading.Tasks.Task<bool> UpdateFornecedorAsync(SOAPServiceReference.Fornecedor fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteFornecedor", ReplyAction="http://tempuri.org/IService/DeleteFornecedorResponse")]
        System.Threading.Tasks.Task<bool> DeleteFornecedorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllProdutos", ReplyAction="http://tempuri.org/IService/GetAllProdutosResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Produto[]> GetAllProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProdutoById", ReplyAction="http://tempuri.org/IService/GetProdutoByIdResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Produto> GetProdutoByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddProduto", ReplyAction="http://tempuri.org/IService/AddProdutoResponse")]
        System.Threading.Tasks.Task<bool> AddProdutoAsync(SOAPServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateProduto", ReplyAction="http://tempuri.org/IService/UpdateProdutoResponse")]
        System.Threading.Tasks.Task<bool> UpdateProdutoAsync(SOAPServiceReference.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteProduto", ReplyAction="http://tempuri.org/IService/DeleteProdutoResponse")]
        System.Threading.Tasks.Task<bool> DeleteProdutoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddEncomenda", ReplyAction="http://tempuri.org/IService/AddEncomendaResponse")]
        System.Threading.Tasks.Task<bool> AddEncomendaAsync(SOAPServiceReference.Encomenda encomenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateEncomendaEstado", ReplyAction="http://tempuri.org/IService/UpdateEncomendaEstadoResponse")]
        System.Threading.Tasks.Task<bool> UpdateEncomendaEstadoAsync(int encomendaId, string novoEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEncomendaById", ReplyAction="http://tempuri.org/IService/GetEncomendaByIdResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Encomenda> GetEncomendaByIdAsync(int encomendaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllEncomendas", ReplyAction="http://tempuri.org/IService/GetAllEncomendasResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Encomenda[]> GetAllEncomendasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllMovimentos", ReplyAction="http://tempuri.org/IService/GetAllMovimentosResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Movimento[]> GetAllMovimentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddMovimento", ReplyAction="http://tempuri.org/IService/AddMovimentoResponse")]
        System.Threading.Tasks.Task<bool> AddMovimentoAsync(SOAPServiceReference.Movimento movimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMovimentosByProduto", ReplyAction="http://tempuri.org/IService/GetMovimentosByProdutoResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Movimento[]> GetMovimentosByProdutoAsync(int produtoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/VerificarStockDisponivel", ReplyAction="http://tempuri.org/IService/VerificarStockDisponivelResponse")]
        System.Threading.Tasks.Task<bool> VerificarStockDisponivelAsync(int produtoId, int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetHistoricoMovimentosByUtilizador", ReplyAction="http://tempuri.org/IService/GetHistoricoMovimentosByUtilizadorResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.Movimento[]> GetHistoricoMovimentosByUtilizadorAsync(int utilizadorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<SOAPServiceReference.User[]> GetAllUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServiceChannel : SOAPServiceReference.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SOAPServiceReference.IService>, SOAPServiceReference.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> TestarConexaoAsync()
        {
            return base.Channel.TestarConexaoAsync();
        }
        
        public System.Threading.Tasks.Task<bool> ValidateUserAsync(string email, string password)
        {
            return base.Channel.ValidateUserAsync(email, password);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.User> GetUserByEmailAsync(string email)
        {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(string nome, string email, string password, string role)
        {
            return base.Channel.AddUserAsync(nome, email, password, role);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Fornecedor[]> GetAllFornecedoresAsync()
        {
            return base.Channel.GetAllFornecedoresAsync();
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Fornecedor> GetFornecedorByIdAsync(int id)
        {
            return base.Channel.GetFornecedorByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddFornecedorAsync(SOAPServiceReference.Fornecedor fornecedor)
        {
            return base.Channel.AddFornecedorAsync(fornecedor);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateFornecedorAsync(SOAPServiceReference.Fornecedor fornecedor)
        {
            return base.Channel.UpdateFornecedorAsync(fornecedor);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteFornecedorAsync(int id)
        {
            return base.Channel.DeleteFornecedorAsync(id);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Produto[]> GetAllProdutosAsync()
        {
            return base.Channel.GetAllProdutosAsync();
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Produto> GetProdutoByIdAsync(int id)
        {
            return base.Channel.GetProdutoByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddProdutoAsync(SOAPServiceReference.Produto produto)
        {
            return base.Channel.AddProdutoAsync(produto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateProdutoAsync(SOAPServiceReference.Produto produto)
        {
            return base.Channel.UpdateProdutoAsync(produto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProdutoAsync(int id)
        {
            return base.Channel.DeleteProdutoAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddEncomendaAsync(SOAPServiceReference.Encomenda encomenda)
        {
            return base.Channel.AddEncomendaAsync(encomenda);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateEncomendaEstadoAsync(int encomendaId, string novoEstado)
        {
            return base.Channel.UpdateEncomendaEstadoAsync(encomendaId, novoEstado);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Encomenda> GetEncomendaByIdAsync(int encomendaId)
        {
            return base.Channel.GetEncomendaByIdAsync(encomendaId);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Encomenda[]> GetAllEncomendasAsync()
        {
            return base.Channel.GetAllEncomendasAsync();
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Movimento[]> GetAllMovimentosAsync()
        {
            return base.Channel.GetAllMovimentosAsync();
        }
        
        public System.Threading.Tasks.Task<bool> AddMovimentoAsync(SOAPServiceReference.Movimento movimento)
        {
            return base.Channel.AddMovimentoAsync(movimento);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Movimento[]> GetMovimentosByProdutoAsync(int produtoId)
        {
            return base.Channel.GetMovimentosByProdutoAsync(produtoId);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarStockDisponivelAsync(int produtoId, int quantidade)
        {
            return base.Channel.VerificarStockDisponivelAsync(produtoId, quantidade);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.Movimento[]> GetHistoricoMovimentosByUtilizadorAsync(int utilizadorId)
        {
            return base.Channel.GetHistoricoMovimentosByUtilizadorAsync(utilizadorId);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceReference.User[]> GetAllUsersAsync()
        {
            return base.Channel.GetAllUsersAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62848/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
